spring.application.name=asanai

spring.datasource.url=jdbc:postgresql://localhost:5432/asanai
spring.datasource.username=postgres
spring.datasource.password=Qwerty12345
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=UnSecretTresLongEtAleatoire1234567890!

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucrandrianjafyy@gmail.com
spring.mail.password=uzhu htfc lyyd yvsx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ai.api.url=https://generativelanguage.googleapis.com
ai.api.key=AIzaSyBHg5Gsox8WPQZQUV3VWJT2iKRGXKY08MM